travis:
  secure:
    BINSTAR_TOKEN: aG37HbeK8lPVJjDSeAJikdAPxLxGOLlWRp/9EJBnD++ctcg8XhDmCu//s/6I8xMC44Ys7SmdCYgdlCXl7kNyTd8TU84UBsey2QAA78Vy5Ol6S1M2b8urSmdaZJotizigGil/EpvOixN3vuWOBzS0c3eXzUQuJMNjsvuJ0sUy03pkCxQy323gX+eaEw+h3vKj9AGBkMPxE3sm6zAbtgkE220kGKUsgolbFAS3hLFbftmi+rUMEok+77FXH5xEI9zF6gO04NKXx//cSMt0bSX5uxovyHqKtCYw97M/yvGgVXR2JFvQil3WYMZ3jQRbrdZYHwRF3i8x7BFWJDIOv6FAQqWOyP4LLbD3uEgoupYtq8clO+5y5JTGjCWsWhAnhhRMa8vu8TXr8Ojeo+ZUPzZRflv9s9sVWJjVtyzxARtX+sT8EqGFw+whq9p4kOz5qhgDtMDK1NfyvStQAId58ORLGpiIJH/UDtdwhf7vU5r7jLTuNksK+5cYEySQbB3+t5mTFuT7X9SYr3IvcWxkwIonPnDJ5SRQOuwlIgRnpSkUP34J2SuHf7c7xUXYBL6US8rCwF2hsS+7+nSi8zYi9a4pSS4QMkxlvQWqIxSf90ivVyweznOp/ZGEf8sYQSF+xfb/XmesYWUdw0lBcpaV1Lvo6Jd9u1Ut/3Ws/CWzeFq0Kqk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
